# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: create-wazuh-packages
on:
  workflow_dispatch:
    inputs:
      wazuh_kibana_app_branch:
        description: 'Branch Kibana App'
        required: true
      wazuh_packages_branch:
        description: 'Branch Wazuh Packages'
        required: true
        default: 'legacy'
      replace_line_install_plugin_dependencies:
        description: 'Line to replace in the Docker/build.sh file that installs the plugin dependencies. Note there is a problem with a subdependency that requires another NodeJS version. It is required ignoring the engines, so the process should not fail. Empty value disable this change.'
        required: true
        default: '123'
jobs:
  setup-wazuh-kibana-app:
    name: Run setup environment wazuh kibana app
    runs-on: ubuntu-18.04
    steps:
     - name: Step 01 - Set up environment
       run: |
        mkdir packages
     - name: Step 02 - Download project wazuh-packages 
       uses: actions/checkout@v2
       with:
        repository: wazuh/wazuh-packages
        ref: ${{ github.event.inputs.wazuh_packages_branch }}
        path: wazuh-packages
     - name: Step 03 - Building package
       run: |
        echo "[info] changing the directory to $GITHUB_WORKSPACE/wazuh-packages/wazuhapp"
        cd $GITHUB_WORKSPACE/wazuh-packages/wazuhapp
        [ -n "${{ github.event.inputs.replace_line_install_plugin_dependencies }}" ] && {
          echo "[info] Replacing string to ignore engines when installing the plugin dependencies in line: ${{ github.event.inputs.replace_line_install_plugin_dependencies }}"
          sed -i '${{ github.event.inputs.replace_line_install_plugin_dependencies }}s|yarn|yarn --ignore-engines|g' ./Docker/build.sh
        }
        echo "[info] running script to generate the plugin package"
        ./generate_wazuh_app.sh -b ${{ github.event.inputs.wazuh_kibana_app_branch }} -s $GITHUB_WORKSPACE/packages -r 1
     - name: Archive packages
       uses: actions/upload-artifact@v2
       with:
        name: wazuh-packages
        path: ${{ github.workspace }}/packages/*
